<div id="altbilgi">
	<div class="ab_bolum" id="hakkimizda">
		<div class="ab_baslik">Hakkımızda</div>
		<ul>
			<li><a href="vizyonumuz.php">Vizyonumuz</a></li>
			<li><a href="misyonumuz.php">Misyonumuz</a></li>
			<li><a href="tarihce.php">Tarihçe</a></li>
			<li><a href="sirket_yapisi.php">Şirket Yapısı</a></li>
		</ul>
	</div>
	<div class="ab_bolum" id="iletisim">
		<div class="ab_baslik">İletişim</div>
		<ul>
			<li><a href="yorum.php">Yorum Bırakın</a></li>
			<li><a href="adres.php">Adres</a></li>
			<li><a href="hr.php">İnsan Kaynakları</a></li>
		</ul>
	</div>
	<div id="ozulhak"> 2014 &copy; Muhammet Mustafa Çalışkan </div>
</div>