<?php include 'baslik.phtml'; ?>
    
    <div id="gobek">
		
		<?php include 'menu.phtml'; ?>
    	
		<div id="icerik">
			<div id="karsilama">
				<div  class="islem_baslik">HOŞGELDİNİZ</div>
				<div id="mesaj">
					<h1>Yönetici Sayfasındasın!</h1>
					<p>Soldaki menülerden siteyi yönetim adına yapabileceğin işlemleri seçebilirsin.</p>
					<p>Düşünmeden hareket etme!</p>
					<p>Kolay gelsin</p>
					<p>Tamam tamam bu kadar yeter.</p>
				</div>
			</div>
		</div><!-- İçerik -->
		<?php include 'altbilgi.phtml'; ?>
    </div><!-- Göbek -->
    
</body>
</html>