<div class="fl_tmr">
	<div class="menu">
		<div class="menu_baslik">TEST OLUŞTURMA</div>
		<ul>
			<li><a href="<?php echo 'admin.php?olustur=resimtesti'; ?>" id="olustur_resim_testi">Resim Testi Oluştur</a></li>
			<li><a href="javascript:void(0);" id="olustur_video_testi">Video Testi Oluştur</a></li>
		</ul>
	</div>
	
	<div class="menu">
		<div class="menu_baslik">
			TEST YÖNETİMİ
		</div>
		<ul>
			<li><a href="<?php echo 'admin.php?yonetim=resimtesti'; ?>" id="resim_testleri">Resim Testleri</a></li>
			<li><a href="javascript:void(0);" id="video_testleri">Video Testleri</a></li>
		</ul>
	</div>
	
	<div class="menu">
		<div class="menu_baslik">
			KULLANICI YÖNETİMİ
		</div>
		<ul>
			<li><a href="javascript:void(0);" id="kullanicilar">Kullanıcılar</a></li>
		</ul>
	</div>
	
	<div class="menu">
		<div class="menu_baslik">
			İSTATİSTİKLER
		</div>
		<ul>
			<li><a href="javascript:void(0);" id="stat_kullanicilar">Kullanıcı İstatistikleri</a></li>
			<li><a href="javascript:void(0);" id="stat_ziyaretler">Sayfa Ziyaretleri</a></li>
			<li><a href="javascript:void(0);" id="stat_test_cevaplamalari">Test Cevaplamaları</a></li>
		</ul>
	</div>
</div>