<?php 
	require_once 'essek/sql/class.Mysql.php';
	
	$talil = new Mysql("talil");
	
	Mysql::sql($talil)
	->select("id as deger, etiket as icerik")
	->from("zorluk")
	->calistir();
	
	if ($talil->etkilenenSatirSayisi > 0)
	{
		$zorluk = $talil->sonuc(true)->alMesaj();
	}
?>

<?php include 'baslik.phtml'; ?>
    
    <div id="gobek">
    	
    	<?php include 'menu.phtml'; ?>
    
		<div id="icerik">
			<div id="test_olustur">
	    		<div class="islem_baslik">
		    		<span>RESİM TESTİ OLUŞTUR</span>
		    		<div class="islem_menu">
	            		<input type="button" class="dugme_islem" value="Yeni" onclick="document.location = 'admin.php?olustur=resimtesti'"/>
	                	<input type="button" class="dugme_islem" id="kaydet" value="Kaydet"/>
	            		<input type="button" class="dugme_islem" value="Vazgeç" onclick="document.location = 'admin.php'"/>
		            </div>
	    		</div>
	    		
	            <div class="form fl_tmr" id="test_bilgileri">
					<div class="form_baslik fl_tmr">
						<span class="_itele">TEST BİLGİLERİ</span>
						<a id="gizle_goster" title="Test Bilgileri formunu gizle/goster">-</a>
					</div>
	                <div class="fl_tmr">
	                	<div class="_uyari_"></div>
	                	<div class="form_alan" id="resim">
	                    	<div class="alan_baslik"><a href="javascript:void(0);" id="resim_ekle">Resim Ekle</a></div>
	                        <img src="" class="_gerekli_" width="150" height="220"/>
	                    </div>
	                    <div class="form_alan" id="etiket"> 
	                    	<div class="alan_baslik">Etiket</div>
	                    	<textarea class="_gerekli_"></textarea>
	                    </div>
	                    <div class="form_alan" id="aciklama">
	                    	<div class="alan_baslik">Açıklama</div>
	                        <textarea class="_gerekli_"></textarea>
	                    </div>
	                	<div class="form_alan" id="zorluk">
	                    	<div class="alan_baslik">Zorluk</div>
	       	    			<select class="_gerekli_">
		       	    			<option value="0" selected>Seçiniz...</option>
		       	    			<?php foreach($zorluk as $z):?>
	       	    				<option value="<?php echo $z["deger"]; ?>"><?php echo $z["icerik"];?></option>
	       	    				<?php endforeach;?>
	                        </select>
	                    </div>
	                    <div class="islemler"></div>
	                </div>
	            </div>
	            <div class="form fl_tmr" id="sorular">
	            	<div class="form_baslik fl_tmr">
	            		<a id="gizle_goster" title="Sorular formunu gizle/goster">-</a>
	            		<span class="_itele">SORULAR</span>
	            	</div>
	                <div class="fl_tmr">
	                	<div class="_uyari_"></div>
						<div class="form_alan" id="soru_yonetimi">
	                    	<div class="alan_baslik">Soru</div>
	                        <div class="alan_alt_baslik">0 sorudan 1. soru</div>
	                        <textarea id="soru" class="_gerekli_"></textarea>
	                   
		                    <div class="alan_baslik">Zorluk </div>
	                        <select id="zorluk" class="_gerekli_"> 
                        		<option value="0" selected>Seçiniz...</option>
                        		<?php foreach($zorluk as $z):?>
       	    						<option value="<?php echo $z["deger"]; ?>"><?php echo $z["icerik"];?></option>
       	    					<?php endforeach;?>
	                        </select>
	                        <label><input type="checkbox"/>Sabit</label>
	                    </div>
	                    <div class="form_alan" id="sik_yonetimi">
	                    	<div class="alan_baslik">Şıklar</div>
	                    	<div id="sik_menu">
	                    		<input type="button" class="siyah_dugme dugme_kck" value="Şık Ekle" id="sik_ekle"/>
	                    		<input type="button" class="siyah_dugme dugme_kck" value="Evet/Hayır" id="evet_hayir"/>
	                    		<label><input type="checkbox"/>Sabit</label>
	                    	</div>
	                        <div id="siklar">
	                        </div>
	                    </div>
	                    <div class="islemler">
	                    	<input type="button" class="siyah_dugme" value="Önceki Soru" id="onceki_soru"/>
	                        <input type="button" class="siyah_dugme" value="Sonraki Soru" id="sonraki_soru"/>
	                        <input type="button" class="siyah_dugme" value="Kaydet ve İlerle" id="kaydet_ilerle"/>
	                    </div>
	                </div>
	            </div>
	        </div>
	    </div>
	    
	    <?php include 'altbilgi.phtml'; ?>
	    
    </div>
    
</body>
</html>