<?php include 'tl_as_ust.phtml'; ?>
<div id="sarma" class="arac_cubugu">
	<div id="baslik">Ayarlar</div>
	<div class="ust_menu fl_tmr">
		<ul class="ayar_menu">
			<li>Çözdüklerim</li>
			<li>İstatistiklerim</li>
			<li>Geçmiş</li>
			<li class="rnk_mn_aktif">Bilgiler</li>
		</ul>
	</div>
	<div class="ust_menu fl_tmr">
		<ul class="ayar_menu">
			<li class="rnk_mn_aktif">Profil</li>
			<li>Güvenlik</li>
			<li>Mesaj Bloke Listesi</li>
		</ul>
	</div>
	<div id="profil" class="fl_tmr">
		<div id="resim" class="p_bolum fl_sl">
			<div class="p_bolum_baslik">
			Profil Resmi
			</div>
			<div class="kutu p_bolum_icerik fl_tmr pdng_1">
				<img src="" class="fl_sl">
				<div class="fl_sg gn_55">
					<input type="button" class="btn_gnl" value="Resim Seç"/>
					<p>Profil resminizi güncelleyin.</p>
					<p>Yükleyeceğiniz resim 4mb 'den büyük olmamalı</p>
				</div>
			</div>
		</div>
		<div class="p_bolum fl_sg">
			<div class="p_bolum_baslik fl_tmr">
				<span class="fl_sl">Kişisel Bilgiler</span>
				<img src="../dznle.png" class="fl_sg el"/>
			</div>
			<div class="kutu p_bolum_icerik pdng_1">
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Ad:</span>
					<span class="deger fl_sg">mustafa</span>
				</div>
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Soyad:</span>
					<span class="deger fl_sg"></span>
				</div>
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Şehir:</span>
					<span class="deger fl_sg">Ağrı</span>
				</div>
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Ülke:</span>
					<span class="deger fl_sg">Türkiye</span>
				</div>
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Facebook:</span>
					<span class="deger fl_sg"></span>
				</div>
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Twitter:</span>
					<span class="deger fl_sg"></span>
				</div>
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Kişisel Web:</span>
					<span class="deger fl_sg"></span>
				</div>
			</div>
		</div>
		<div class="p_bolum fl_sl">
			<div class="p_bolum_baslik fl_tmr">
				<span class="fl_sl">Hesap</span>
				<img src="../dznle.png" class="fl_sg el"/>
			</div>
			<div class="kutu p_bolum_icerik pdng_1">
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Kullanıcı Adı:</span>
					<span class="deger fl_sg">mustafa22333</span>
				</div>
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Email:</span>
					<span class="deger fl_sg">muhammetmustafa25...</span>
				</div>
			</div>
		</div>
	</div>
</div>