<div id="sarma" class="arac_cubugu">
	<div id="baslik">Ayarlar</div>
	<div class="ust_menu fl_tmr">
		<ul class="ayar_menu">
			<li>Çözdüklerim</li>
			<li>İstatistiklerim</li>
			<li>Geçmiş</li>
			<li class="rnk_mn_aktif">Bilgiler</li>
		</ul>
	</div>
	<div class="ust_menu fl_tmr">
		<ul class="ayar_menu">
			<li>Profil</li>
			<li>Güvenlik</li>
			<li class="rnk_mn_aktif">Mesaj Bloke Listesi</li>
		</ul>
	</div>
	<div id="profil" class="fl_tmr">
		<div class="rnk_btn_arka liste">
			<table>
				<thead>
					<tr>
						<th><input type="checkbox"/></th>
						<th></th>
						<th class="gn_45">Kullanıcı</th>
						<th class="gn_50">Bloke Tarihi</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><input type="checkbox"/></td>
						<td>1</td>
						<td>aumem33</td>
						<td>21/50/28282 33:34:334</td>
					</tr>
					<tr>
						<td><input type="checkbox"/></td>
						<td>1</td>
						<td>aumem33</td>
						<td>21/50/28282 33:34:334</td>
					</tr>
					<tr>
						<td><input type="checkbox"/></td>
						<td>1</td>
						<td>aumem33</td>
						<td>21/50/28282 33:34:334</td>
					</tr>
					<tr>
						<td><input type="checkbox"/></td>
						<td>1</td>
						<td>aumem33</td>
						<td>21/50/28282 33:34:334</td>
					</tr>
					<tr>
						<td><input type="checkbox"/></td>
						<td>1</td>
						<td>aumem33</td>
						<td>21/50/28282 33:34:334</td>
					</tr>
				</tbody>
			</table>
			<div id="islem">
				Seçilileri
				<select>
					<option selected value="0">İşlem Seçiniz...</option>
					<option value="1">Sil</option>
					<option value="2">Okunmuş İşaretle</option>
					<option value="3">Okunmamış İşaretle</option>
				</select>
				<input type="button" class="btn_gnl" value="Git"/>
			</div>
			<div id="navigasyon" class="t_orta navigasyon">
				<div id="once">
					<a href="javascript:void(0);" id="en_ilk">&lt;&lt;</a>
					<a href="javascript:void(0);" id="onceki" class="nav_bosluk">&lt;</a>
				</div>
				<div id="sayilar" class="nav_sayilar_bosluk">
					<a href="javascript:void(0);">1</a>
					<a href="javascript:void(0);">2</a>
					<a href="javascript:void(0);">3</a>
					<a href="javascript:void(0);">4</a>
					<a href="javascript:void(0);">5</a>
				</div>
				<div id="sonra">
					<a href="javascript:void(0);" id="sonraki">&gt;</a>
					<a href="javascript:void(0);" id="en_son" class="nav_bosluk">&gt;&gt;</a>
				</div>
			</div>
		</div>
	</div>
</div>