<?php include 'tl_as_ust.phtml'; ?>
<div id="sarma" class="arac_cubugu">
	<div id="baslik">Ayarlar</div>
	<div class="ust_menu fl_tmr">
		<ul class="ayar_menu">
			<li>Çözdüklerim</li>
			<li class="rnk_mn_aktif">İstatistiklerim</li>
			<li>Geçmiş</li>
			<li>Bilgiler</li>
		</ul>
	</div>
	<div id="istatistikler">
		<p><b>Cevaplanan Test Sayısı:</b> 2</p>
		<p><b>Cevapları Kaydedilen Test Sayısı:</b> 23</p>
	</div>
</div>