<td width="75" height="110">
	<img src="<?php echo $sonuc["resim_dizini"].$sonuc["resim_adi"];?>" 
		 width="<?php echo $sonuc["genislik"];?>" 
		 height="<?php echo $sonuc["yukseklik"];?>"/>
</td>
<td><?php echo $id;?></td>
<td><?php echo $sonuc["etiket"];?></td>
<td><?php echo $sonuc["aciklama"];?></td>
<td><?php echo $sonuc["tarih"];?></td>
<td><?php echo $sonuc["zetiket"];?></td>
<td class="">
	<input type="button" class="kiremit_dugme" id="duzenle_test" value="Düzenle"/>
	<input type="button" class="kiremit_dugme" id="testi_sil" value="Testi Sil"/>
	<input type="button" class="kiremit_dugme" id="bilgiler" value="Bilgiler"/>
</td>
			