<div id="bas" class="fl_tmr genislik">
	<div id="bas_sol" class="fl_sl">
		<a href="/talil" title="Talil" class="rnk_logo">TAL'İL*</a>
	</div>
	<div id="bas_sag" class="fl_sg">
		<form id="giris" class="fl_tmr">
			<div><label for="k_adi_email">Kullanıcı Adı/Email:</label><input type="text" name="k_adi_email" class="_gerekli_"/></div>
			<div><label for="sifre">Şifre:</label><input type="password" name="sifre" class="_gerekli_"/></div>
			<div id="grs_dgm">
				<label class="fl_nn"><input type="checkbox" name="beni_hatirla" id="beni_hatirla" class="fl_nn"/>Beni Hatırla</label>
				<input type="submit" value="Giriş" id="kayit_ol"/>
			</div>
		</form>
	</div>
</div>
<div id="indx_icerik" class="genislik">
	
	<div id="hos" class="kutu fl_tmr rnk_mtn">
		<div id="hos_sol" class="fl_sl">
			<h1>Hoşgeldiniz</h1>
			<p>Talil, “leb” demeden “çorum” diyebilenlerin platformudur. 
			Burada çeşitli testlerle yeteneklerinizi keşfedebilirsiniz ve geliştirebilirsiniz.
			</p>
		</div>
		<div id="hos_sag" class="fl_sg">
			<p id="form_baslik">Kayıt</p>
			<form id="kayit">
				<div><label for="k_adi">Kullanıcı Adı:</label><input type="text" name="k_adi" class="_gerekli_"/></div>
				<div><label for="email">Email:</label> <input type="text" name="email" class="_gerekli_"/></div>
				<div><label for="sifre">Şifre:</label><input type="password" name="sifre" class="_gerekli_"/></div>
				<div><label for="sifre_tekrar">Şifre Tekrar:</label><input type="password" name="sifre_tekrar" class="_gerekli_"/></div>
				<div><input type="submit" value="Kayıt" id="kayit_ol"/></div>
			</form>
		</div>
	</div>
	
	<div id="altbilgi" class="kutu">
		<div id="bolumler" class="fl_tmr">
			<div class="bolum fl_sl">
				<div class="blm_baslik rnk_ab_bslk">
					Hakkımızda
				</div>
				<ul>
					<li><a href="javascript:void(0);">Vizyonumuz</a></li>
					<li><a href="javascript:void(0);">Misyonumuz</a></li>
					<li><a href="javascript:void(0);">Tarihçe</a></li>
					<li><a href="javascript:void(0);">Şirket Yapısı</a></li>
				</ul>
			</div>
			<div class="bolum fl_sg">
				<div class="blm_baslik rnk_ab_bslk">
					İletişim
				</div>
				<ul>
					<li><a href="javascript:void(0);">Yorum</a></li>
					<li><a href="javascript:void(0);">Adres</a></li>
					<li><a href="javascript:void(0);">İnsan Kaynakları</a></li>
					<li><a href="javascript:void(0);">Site Haritası</a></li>
				</ul>
			</div>
		</div>
		<div id="ozulhak">
			2014 &copy; Muhammet Mustafa Çalışkan 
		</div>
	</div>
	<div id="sozluk" class="">
		
		* isim, eskimiş (ta:lil) Arapça ta¤l³l<br /><br />
		1 .   Sebep gösterme.<br />   
		2 .   felsefe  Tümden gelim.
		
	</div>
</div>