<div id="dolma" class="arac_cubugu fl_tmr">
	<?php include_once 'tl_as_menu.phtml'; ?>
	<div id="icerik">
		<div id="arama">
			<div id="arama_baslik">
				<span>"falan filan"</span> Arama Sonuçları (21)
			</div>
			<div id="sonuclar">
				<div class="sonuc fl_tmr">
					<img />
					<div class="bilgiler">
						<span class="id">#25</span>
						<span class="etiket">uie tauieak yuimkea yulmike</span>
						<input type="button" class="btn_gnl" value="Çöz"/>
					</div>
	 			</div>
	 			<div class="sonuc fl_tmr">
					<img />
					<div class="bilgiler">
						<span class="id">#35</span>
						<span class="etiket">uie uieea yulmike</span>
						<input type="button" class="btn_gnl" value="Çöz"/>
					</div>
	 			</div>
	 			<div class="sonuc fl_tmr">
					<img />
					<div class="bilgiler">
					<span class="id">#35</span>
					<span class="etiket">uie uieea yulmike</span>
					<input type="button" class="btn_gnl" value="Çöz"/>
					</div>
	 			</div>
	 			<div class="sonuc fl_tmr">
					<img />
					<div class="bilgiler">
					<span class="id">#35</span>
					<span class="etiket">uie uieea yulmike</span>
					<input type="button" class="btn_gnl" value="Çöz"/>
					</div>
	 			</div>
	 			<div class="sonuc fl_tmr">
					<img />
					<div class="bilgiler">
					<span class="id">#35</span>
					<span class="etiket">uie uieea yulmike</span>
					<input type="button" class="btn_gnl" value="Çöz"/>
					</div>
	 			</div>
			</div>
			<input type="button" class="btn_gnl" value="Daha fazla..."/>
		</div>
	</div>
</div>