<?php include 'tl_as_ust.phtml'; ?>
<div id="sarma" class="arac_cubugu">
	<div id="baslik">Ayarlar</div>
	<div class="ust_menu fl_tmr">
		<ul class="ayar_menu">
			<li class="rnk_mn_aktif">Çözdüklerim</li>
			<li>İstatistiklerim</li>
			<li>Geçmiş</li>
			<li>Bilgiler</li>
		</ul>
	</div>
	<div id="testler">
		<div class="rnk_btn_arka liste">
			<table>
				<thead>
					<tr>
						<th></th>
						<th id="etiket">Etiket</th>
						<th id="aciklama">Açıklama</th>
						<th id="c_tarihi">Cevaplama Tarihi</th>
						<th id="kategori">Kategori</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>#24</td>
						<td>aulimeak2</td>
						<td>umli keyuam kiemak uimkgnhkğ mk ui</td>
						<td>21/50/28282 33:34:334</td>
						<td>Bilim</td>
					</tr>
					<tr>
						<td>#24</td>
						<td>aulimeak2</td>
						<td>umli keyuam kiemak uimkgnhkğ mk ui</td>
						<td>21/50/28282 33:34:334</td>
						<td>Bilim</td>
					</tr>
					<tr>
						<td>#24</td>
						<td>aulimeak2</td>
						<td>umli keyuam kiemak uimkgnhkğ mk ui</td>
						<td>21/50/28282 33:34:334</td>
						<td>Bilim</td>
					</tr>
					<tr>
						<td>#24</td>
						<td>aulimeak2</td>
						<td>umli keyuam kiemak uimkgnhkğ mk ui</td>
						<td>21/50/28282 33:34:334</td>
						<td>Bilim</td>
					</tr>
				</tbody>
			</table>
			<div id="navigasyon" class="t_orta navigasyon">
				<div id="once">
					<a href="javascript:void(0);" id="en_ilk">&lt;&lt;</a>
					<a href="javascript:void(0);" id="onceki" class="nav_bosluk">&lt;</a>
				</div>
				<div id="sayilar" class="nav_sayilar_bosluk">
					<a href="javascript:void(0);">1</a>
					<a href="javascript:void(0);">2</a>
					<a href="javascript:void(0);">3</a>
					<a href="javascript:void(0);">4</a>
					<a href="javascript:void(0);">5</a>
				</div>
				<div id="sonra">
					<a href="javascript:void(0);" id="sonraki">&gt;</a>
					<a href="javascript:void(0);" id="en_son" class="nav_bosluk">&gt;&gt;</a>
				</div>
			</div>
		</div>
	</div>
</div>