<?php include 'tl_as_ust.phtml'; ?>
<div id="sarma" class="arac_cubugu">
	<div id="baslik">Ayarlar</div>
	<div class="ust_menu fl_tmr">
		<ul class="ayar_menu">
			<li>Çözdüklerim</li>
			<li>İstatistiklerim</li>
			<li>Geçmiş</li>
			<li class="rnk_mn_aktif">Bilgiler</li>
		</ul>
	</div>
	<div class="ust_menu fl_tmr">
		<ul class="ayar_menu">
			<li>Profil</li>
			<li class="rnk_mn_aktif">Güvenlik</li>
			<li>Mesaj Bloke Listesi</li>
		</ul>
	</div>
	<div id="profil" class="fl_tmr">
		<div class="p_bolum fl_sl">
			<div class="p_bolum_baslik fl_tmr">
				<span class="fl_sl">Şifre</span>
			</div>
			<div class="kutu p_bolum_icerik pdng_1">
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Eski Şifre:</span>
					<span class="deger fl_sg"><input type="text" /></span>
				</div>
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Yeni Şifre:</span>
					<span class="deger fl_sg"><input type="text" /></span>
				</div>
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Yeni Şifre Tekrar:</span>
					<span class="deger fl_sg"><input type="text" /></span>
				</div>
				<div class="bilgi_satir fl_tmr">
					<span class="deger fl_sg"><input type="button" value="Kaydet" class="btn_gnl"/></span>
				</div>
			</div>
		</div>
	</div>
</div>