<div id="dolma" class="arac_cubugu fl_tmr">
	<?php include_once 'tl_as_menu.phtml'; ?>
	<div id="icerik">
		<div id="test">
			<div id="bilgiler">
				<span><b>Test No: #222</b> - Falan Filan</span>
				<span class="kydr_sg_4"><b>Kategori:</b>Bilim</span>
			</div>
			<div id="soru" class="kutu">
				<img>
				<div id="soru_icerik">
					<p id="soru_konum"><b>1</b>/24</p>
					<p id="soru_metin">umieyk amkuygğmk ahuikeylakm uiymek auygğnhk uikay umlikeamlu?</p>
					<div id="siklar">
						<div><label><input type="radio" name="cevap"/><span><b>A) </b>uieka ylmuikeyaml kuyilmka yuimle</span></label></div>
						<div><label><input type="radio" name="cevap"/><span><b>A) </b>uiüi ea kuyilmka yuimle</span></label></div>
						<div><label><input type="radio" name="cevap"/><span><b>A) </b>uieüyilmka yuimle</span></label></div>
						<div><label><input type="radio" name="cevap"/><span><b>A) </b>uieka ylmuikeyaml kuyilmka yuimle</span></label></div>
						<div><label><input type="radio" name="cevap"/><span><b>A) </b>uiüi ea kuyilmka yuimle</span></label></div>
						<div><label><input type="radio" name="cevap"/><span><b>A) </b>uieüyilmka yuimle</span></label></div>
						<div><label><input type="radio" name="cevap"/><span><b>A) </b>uieka ylmuikeyaml kuyilmka yuimle</span></label></div>
						<div><label><input type="radio" name="cevap"/><span><b>A) </b>uiüi ea kuyilmka yuimle</span></label></div>
						<div><label><input type="radio" name="cevap"/><span><b>A) </b>uieüyilmka yuimle</span></label></div>
					</div>
				</div>
			</div>
			<div id="soru_navigasyon" class="rnk_mn_arka t_orta">
				<input type="button" class="btn_gnl" value="Önceki Soru"/>
				<input type="button" class="btn_gnl" value="Sonraki Soru"/>
			</div>
			<div id="islemler">
				<ul>
					<li><input type="button" class="btn_gnl" value="Cevaplarımı Kaydet"/></li>
					<li class="aciklama">* test çözümüne daha sonra devam etmeniz için verdiğiniz cevapları kaydededer.</li>
					<li><input type="button" class="btn_gnl" value="Cevaplarımı Gönder"/></li>
					<li class="aciklama">* cevaplarınızı değerlendirmek üzere gönderir. Bu işlemi geri alamazsınız.</li>
					<li><input type="button" class="btn_gnl" value="Vazgeç"/></li>
				</ul>
			</div>
		</div>
	</div>
</div>