<div id="dolma" class="arac_cubugu fl_tmr">
	<?php include_once 'tl_as_menu.phtml'; ?>
	<div id="icerik" class="fl_tmr">
		<div id="test_akisi">
			<div class="akis">
				<div class="akis_baslik">Son Eklenenler</div>
				<div class="akis_testler fl_tmr">
					<div class="test kutu fl_tmr fl_sl">
						<img src="" class="fl_sl"/>
						<div class="test_bilgileri">
							<p class="tb_etiket">Falan Filan</p>
							<p class="tb_aciklama">uylim akuyilm ekauyimlk yulmikea yumli</p>
						</div>
						<div class="test_alt_menu">
							<input type="button" class="btn_gnl fl_sg" value="Çöz" />
						</div> 
					</div>
					<div class="test kutu fl_tmr fl_sg">
						<img src="" class="fl_sl"/>
						<div class="test_bilgileri">
							<p class="tb_etiket">Falui eauie </p>
							<p class="tb_aciklama">auie auie auie auie auiea ugğ augğ auia uiea uieayumli</p>
						</div>
						<div class="test_alt_menu">
							<input type="button" class="btn_gnl fl_sg" value="Çöz" />
						</div> 
					</div>
					<div class="test kutu fl_tmr fl_sl">
						<img src="" class="fl_sl"/>
						<div class="test_bilgileri">
							<p class="tb_etiket">Faluauie auie eauie </p>
							<p class="tb_aciklama">auie auie auie auie auiea ugğ augğ auia uiea uieayumli</p>
						</div>
						<div class="test_alt_menu">
							<input type="button" class="btn_gnl fl_sg" value="Çöz" />
						</div> 
					</div>
				</div>
			</div>
			<div class="akis">
				<div class="akis_baslik">En Son Çözülenler</div>
				<div class="akis_testler fl_tmr">
					<div class="test kutu fl_tmr fl_sl">
						<img src="" class="fl_sl"/>
						<div class="test_bilgileri">
							<p class="tb_etiket">Falan Filan</p>
							<p class="tb_aciklama">uylim akuyilm ekauyimlk yulmikea yumli</p>
						</div>
						<div class="test_alt_menu">
							<input type="button" class="btn_gnl fl_sg" value="Çöz" />
						</div> 
					</div>
					<div class="test kutu fl_tmr fl_sg">
						<img src="" class="fl_sl"/>
						<div class="test_bilgileri">
							<p class="tb_etiket">Falui eauie </p>
							<p class="tb_aciklama">auie auie auie auie auiea ugğ augğ auia uiea uieayumli</p>
						</div>
						<div class="test_alt_menu">
							<input type="button" class="btn_gnl fl_sg" value="Çöz" />
						</div> 
					</div>
					<div class="test kutu fl_tmr fl_sl">
						<img src="" class="fl_sl"/>
						<div class="test_bilgileri">
							<p class="tb_etiket">Falui eauie </p>
							<p class="tb_aciklama">auie auie auie auie auiea ugğ augğ auia uiea uieayumli</p>
						</div>
						<div class="test_alt_menu">
							<input type="button" class="btn_gnl fl_sg" value="Çöz" />
						</div> 
					</div>
				</div>
			</div>
		</div>
		<div id="listeler" class="kutu">
			<div class="liste">
				<div class="liste_baslik">
					En Çok Test Çözenler
				</div>
				<ul>
					<li>maemk234</li>
					<li>aeiğğ3</li>
					<li>maemieauk234</li>
					<li>maem uik234</li>
					<li>maeuie mk234</li>
					<li>mauie aemk234</li>
				</ul>
			</div>
			<div class="liste">
				<div class="liste_baslik">
					En Çok Çözülen Testler
				</div>
				<ul>
					<li>uağa</li>
					<li>aeui eaiğğ3</li>
					<li>mauu ie iea3emieauk234</li>
					<li>maeu ieaum uik234</li>
					<li>maeu iea uuie mk234</li>
					<li>mauui eaie aemk234</li>
				</ul>
			</div>
		</div>
	</div>
</div>