<div id="ust_arac_cubugu" class="fl_tmr arac_cubugu">
	<div id="logo_t">
		<img src="../t.png"/>
	</div>
	<div id="uac_menu" class="fl_tmr">
		<div id="arama">
			<input type="text" id="txt_arama" name="nm_arama" class="rnk_inpt_txt_arka"/>
			<img src="../ara.png" id="ara"/>
		</div>
		<ul id="gosterge">
			<li class="tabela tbl_pd rnk_tbl_arka uac_ic_ktlr_mrgn">
				<div class="tbl_bslk">Puan</div>
				<div class="tbl_dgr">23423423</div>
			</li>
			<li class="tabela tbl_pd rnk_tbl_arka uac_ic_ktlr_mrgn">
				<div class="tbl_bslk">Seviye</div>
				<div class="tbl_dgr">Watson</div>
			</li>
			<li id="klnc_yn_kt" class="rnk_tbl_arka uac_ic_ktlr_mrgn">
				<div id="klnc_resim"><img src="../bunyo.jpg"/></div>
				<div id="yn_kt" class="fl_tmr">
					<div id="klnc_adi" class="rnk_klnc_yn_kt_klnc_adi el_goster">mustafa2511</div>
					<ul class="tbl_pd">
						<li id="msj" title="Mesajlar"></li>
						<li id="ayr" title="Ayarlar"></li>
						<li id="cks" title="Çýkýþ"></li>
					</ul>
				</div>
			</li>
		</ul>
	</div>
</div>
<div class="ust_menu fl_tmr arac_cubugu">
	<ul>
		<li>Yeni Eklenenler</li>
		<li>Favoriler</li>
		<li>En Çok Çözülenler</li>
	</ul>
</div>