<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<link rel="stylesheet" type="text/css" href="../css/ilklendirme.css"/>
<link rel="stylesheet" type="text/css" href="../css/talil_ortak.css"/>
<link rel="stylesheet" type="text/css" href="../css/talil_ayarlar.css"/>
<link rel="stylesheet" type="text/css" href="../css/zabita.css"/>
<body>
<div id="ust_arac_cubugu" class="fl_tmr arac_cubugu">
	<div id="logo_t">
		<img src="../t.png"/>
	</div>
	<div id="uac_menu" class="fl_tmr">
		<div id="arama">
			<input type="text" id="txt_arama" name="nm_arama" class="rnk_inpt_txt_arka"/>
			<img src="../ara.png" id="ara"/>
		</div>
		<ul id="gosterge">
			<li class="tabela tbl_pd rnk_tbl_arka uac_ic_ktlr_mrgn">
				<div class="tbl_bslk">Puan</div>
				<div class="tbl_dgr">23423423</div>
			</li>
			<li class="tabela tbl_pd rnk_tbl_arka uac_ic_ktlr_mrgn">
				<div class="tbl_bslk">Seviye</div>
				<div class="tbl_dgr">Watson</div>
			</li>
			<li id="klnc_yn_kt" class="rnk_tbl_arka uac_ic_ktlr_mrgn">
				<div id="klnc_resim"><img src="../bunyo.jpg"/></div>
				<div id="yn_kt" class="fl_tmr">
					<div id="klnc_adi" class="rnk_klnc_yn_kt_klnc_adi el_goster">mustafa2511</div>
					<ul class="tbl_pd">
						<li id="msj" title="Mesajlar"></li>
						<li id="ayr" title="Ayarlar"></li>
						<li id="cks" title="Çıkış"></li>
					</ul>
				</div>
			</li>
		</ul>
	</div>
</div>
<div id="sarma" class="arac_cubugu">
	<div id="baslik">Ayarlar</div>
	<div class="ust_menu fl_tmr">
		<ul class="ayar_menu">
			<li>Çözdüklerim</li>
			<li>İstatistiklerim</li>
			<li>Geçmiş</li>
			<li class="rnk_mn_aktif">Bilgiler</li>
		</ul>
	</div>
	<div class="ust_menu fl_tmr">
		<ul class="ayar_menu">
			<li>Profil</li>
			<li>Güvenlik</li>
			<li class="rnk_mn_aktif">Mesaj Bloke Listesi</li>
		</ul>
	</div>
	<div id="profil" class="fl_tmr">
		<div class="rnk_btn_arka liste">
			<table>
				<thead>
					<tr>
						<th><input type="checkbox"/></th>
						<th></th>
						<th class="gn_45">Kullanıcı</th>
						<th class="gn_50">Bloke Tarihi</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><input type="checkbox"/></td>
						<td>1</td>
						<td>aumem33</td>
						<td>21/50/28282 33:34:334</td>
					</tr>
					<tr>
						<td><input type="checkbox"/></td>
						<td>1</td>
						<td>aumem33</td>
						<td>21/50/28282 33:34:334</td>
					</tr>
					<tr>
						<td><input type="checkbox"/></td>
						<td>1</td>
						<td>aumem33</td>
						<td>21/50/28282 33:34:334</td>
					</tr>
					<tr>
						<td><input type="checkbox"/></td>
						<td>1</td>
						<td>aumem33</td>
						<td>21/50/28282 33:34:334</td>
					</tr>
					<tr>
						<td><input type="checkbox"/></td>
						<td>1</td>
						<td>aumem33</td>
						<td>21/50/28282 33:34:334</td>
					</tr>
				</tbody>
			</table>
			<div id="islem">
				Seçilileri
				<select>
					<option selected value="0">İşlem Seçiniz...</option>
					<option value="1">Sil</option>
					<option value="2">Okunmuş İşaretle</option>
					<option value="3">Okunmamış İşaretle</option>
				</select>
				<input type="button" class="btn_gnl" value="Git"/>
			</div>
			<div id="navigasyon" class="t_orta navigasyon">
				<div id="once">
					<a href="javascript:void(0);" id="en_ilk">&lt;&lt;</a>
					<a href="javascript:void(0);" id="onceki" class="nav_bosluk">&lt;</a>
				</div>
				<div id="sayilar" class="nav_sayilar_bosluk">
					<a href="javascript:void(0);">1</a>
					<a href="javascript:void(0);">2</a>
					<a href="javascript:void(0);">3</a>
					<a href="javascript:void(0);">4</a>
					<a href="javascript:void(0);">5</a>
				</div>
				<div id="sonra">
					<a href="javascript:void(0);" id="sonraki">&gt;</a>
					<a href="javascript:void(0);" id="en_son" class="nav_bosluk">&gt;&gt;</a>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>