<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<link rel="stylesheet" type="text/css" href="../css/ilklendirme.css"/>
<link rel="stylesheet" type="text/css" href="../css/talil_ortak.css"/>
<link rel="stylesheet" type="text/css" href="../css/talil_ayarlar.css"/>
<link rel="stylesheet" type="text/css" href="../css/zabita.css"/>
<body>
<div id="ust_arac_cubugu" class="fl_tmr arac_cubugu">
	<div id="logo_t">
		<img src="../t.png"/>
	</div>
	<div id="uac_menu" class="fl_tmr">
		<div id="arama">
			<input type="text" id="txt_arama" name="nm_arama" class="rnk_inpt_txt_arka"/>
			<img src="../ara.png" id="ara"/>
		</div>
		<ul id="gosterge">
			<li class="tabela tbl_pd rnk_tbl_arka uac_ic_ktlr_mrgn">
				<div class="tbl_bslk">Puan</div>
				<div class="tbl_dgr">23423423</div>
			</li>
			<li class="tabela tbl_pd rnk_tbl_arka uac_ic_ktlr_mrgn">
				<div class="tbl_bslk">Seviye</div>
				<div class="tbl_dgr">Watson</div>
			</li>
			<li id="klnc_yn_kt" class="rnk_tbl_arka uac_ic_ktlr_mrgn">
				<div id="klnc_resim"><img src="../bunyo.jpg"/></div>
				<div id="yn_kt" class="fl_tmr">
					<div id="klnc_adi" class="rnk_klnc_yn_kt_klnc_adi el_goster">mustafa2511</div>
					<ul class="tbl_pd">
						<li id="msj" title="Mesajlar"></li>
						<li id="ayr" title="Ayarlar"></li>
						<li id="cks" title="Çıkış"></li>
					</ul>
				</div>
			</li>
		</ul>
	</div>
</div>
<div id="sarma" class="arac_cubugu">
	<div id="baslik">Ayarlar</div>
	<div class="ust_menu fl_tmr">
		<ul class="ayar_menu">
			<li>Çözdüklerim</li>
			<li>İstatistiklerim</li>
			<li>Geçmiş</li>
			<li class="rnk_mn_aktif">Bilgiler</li>
		</ul>
	</div>
	<div class="ust_menu fl_tmr">
		<ul class="ayar_menu">
			<li class="rnk_mn_aktif">Profil</li>
			<li>Güvenlik</li>
			<li>Mesaj Bloke Listesi</li>
		</ul>
	</div>
	<div id="profil" class="fl_tmr">
		<div id="resim" class="p_bolum fl_sl">
			<div class="p_bolum_baslik">
			Profil Resmi
			</div>
			<div class="kutu p_bolum_icerik fl_tmr pdng_1">
				<img src="" class="fl_sl">
				<div class="fl_sg gn_55">
					<input type="button" class="btn_gnl" value="Resim Seç"/>
					<p>Profil resminizi güncelleyin.</p>
					<p>Yükleyeceğiniz resim 4mb 'den büyük olmamalı</p>
				</div>
			</div>
		</div>
		<div class="p_bolum fl_sg">
			<div class="p_bolum_baslik fl_tmr">
				<span class="fl_sl">Kişisel Bilgiler</span>
				<img src="../dznle.png" class="fl_sg el"/>
			</div>
			<div class="kutu p_bolum_icerik pdng_1">
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Ad:</span>
					<span class="deger fl_sg">mustafa</span>
				</div>
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Soyad:</span>
					<span class="deger fl_sg"></span>
				</div>
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Şehir:</span>
					<span class="deger fl_sg">Ağrı</span>
				</div>
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Ülke:</span>
					<span class="deger fl_sg">Türkiye</span>
				</div>
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Facebook:</span>
					<span class="deger fl_sg"></span>
				</div>
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Twitter:</span>
					<span class="deger fl_sg"></span>
				</div>
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Kişisel Web:</span>
					<span class="deger fl_sg"></span>
				</div>
			</div>
		</div>
		<div class="p_bolum fl_sl">
			<div class="p_bolum_baslik fl_tmr">
				<span class="fl_sl">Hesap</span>
				<img src="../dznle.png" class="fl_sg el"/>
			</div>
			<div class="kutu p_bolum_icerik pdng_1">
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Kullanıcı Adı:</span>
					<span class="deger fl_sg">mustafa22333</span>
				</div>
				<div class="bilgi_satir fl_tmr">
					<span class="ozellik fl_sl">Email:</span>
					<span class="deger fl_sg">muhammetmustafa25...</span>
				</div>
			</div>
		</div>
	</div>
</div>
</body>
</html>