<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<link rel="stylesheet" type="text/css" href="../css/ilklendirme.css"/>
<link rel="stylesheet" type="text/css" href="../css/talil_ortak.css"/>
<link rel="stylesheet" type="text/css" href="../css/talil_anasayfa.css"/>
<link rel="stylesheet" type="text/css" href="../css/zabita.css"/>
<body>
<div id="ust_arac_cubugu" class="fl_tmr arac_cubugu">
	<div id="logo_t">
		<img src="../t.png"/>
	</div>
	<div id="uac_menu" class="fl_tmr">
		<div id="arama">
			<input type="text" id="txt_arama" name="nm_arama" class="rnk_inpt_txt_arka"/>
			<img src="../ara.png" id="ara"/>
		</div>
		<ul id="gosterge">
			<li class="tabela tbl_pd rnk_tbl_arka uac_ic_ktlr_mrgn">
				<div class="tbl_bslk">Puan</div>
				<div class="tbl_dgr">23423423</div>
			</li>
			<li class="tabela tbl_pd rnk_tbl_arka uac_ic_ktlr_mrgn">
				<div class="tbl_bslk">Seviye</div>
				<div class="tbl_dgr">Watson</div>
			</li>
			<li id="klnc_yn_kt" class="rnk_tbl_arka uac_ic_ktlr_mrgn">
				<div id="klnc_resim"><img src="../bunyo.jpg"/></div>
				<div id="yn_kt" class="fl_tmr">
					<div id="klnc_adi" class="rnk_klnc_yn_kt_klnc_adi el_goster">mustafa2511</div>
					<ul class="tbl_pd">
						<li id="msj" title="Mesajlar"></li>
						<li id="ayr" title="Ayarlar"></li>
						<li id="cks" title="Çıkış"></li>
					</ul>
				</div>
			</li>
		</ul>
	</div>
</div>
<div class="ust_menu fl_tmr arac_cubugu">
	<ul>
		<li>Yeni Eklenenler</li>
		<li>Favoriler</li>
		<li>En Çok Çözülenler</li>
	</ul>
</div>
<div id="dolma" class="arac_cubugu fl_tmr">
	<div id="menu">
		<dl>
			<dt>Kategoriler</dt>
			<dd>
				<ul>
					<li>Bilim</li>
					<li>Sanat</li>
					<li>Politika/Siyaset</li>
					<li>Müzik</li>
					<li>Film</li>
				</ul>
			</dd>
		</dl>
	</div>
	<div id="icerik">
		<div id="arama">
			<div id="arama_baslik">
				<span>"falan filan"</span> Arama Sonuçları (21)
			</div>
			<div id="sonuclar">
				<div class="sonuc fl_tmr">
					<img />
					<div class="bilgiler">
						<span class="id">#25</span>
						<span class="etiket">uie tauieak yuimkea yulmike</span>
						<input type="button" class="btn_gnl" value="Çöz"/>
					</div>
	 			</div>
	 			<div class="sonuc fl_tmr">
					<img />
					<div class="bilgiler">
						<span class="id">#35</span>
						<span class="etiket">uie uieea yulmike</span>
						<input type="button" class="btn_gnl" value="Çöz"/>
					</div>
	 			</div>
	 			<div class="sonuc fl_tmr">
					<img />
					<div class="bilgiler">
					<span class="id">#35</span>
					<span class="etiket">uie uieea yulmike</span>
					<input type="button" class="btn_gnl" value="Çöz"/>
					</div>
	 			</div>
	 			<div class="sonuc fl_tmr">
					<img />
					<div class="bilgiler">
					<span class="id">#35</span>
					<span class="etiket">uie uieea yulmike</span>
					<input type="button" class="btn_gnl" value="Çöz"/>
					</div>
	 			</div>
	 			<div class="sonuc fl_tmr">
					<img />
					<div class="bilgiler">
					<span class="id">#35</span>
					<span class="etiket">uie uieea yulmike</span>
					<input type="button" class="btn_gnl" value="Çöz"/>
					</div>
	 			</div>
			</div>
			<input type="button" class="btn_gnl" value="Daha fazla..."/>
		</div>
	</div>
</div>
</body>
</html>