<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<link rel="stylesheet" type="text/css" href="../css/ilklendirme.css"/>
<link rel="stylesheet" type="text/css" href="../css/talil_ortak.css"/>
<link rel="stylesheet" type="text/css" href="../css/talil_anasayfa.css"/>
<link rel="stylesheet" type="text/css" href="../css/zabita.css"/>
<body>
<div id="ust_arac_cubugu" class="fl_tmr arac_cubugu">
	<div id="logo_t">
		<img src="../t.png"/>
	</div>
	<div id="uac_menu" class="fl_tmr">
		<div id="arama">
			<input type="text" id="txt_arama" name="nm_arama" class="rnk_inpt_txt_arka"/>
			<img src="../ara.png" id="ara"/>
		</div>
		<ul id="gosterge">
			<li class="tabela tbl_pd rnk_tbl_arka uac_ic_ktlr_mrgn">
				<div class="tbl_bslk">Puan</div>
				<div class="tbl_dgr">23423423</div>
			</li>
			<li class="tabela tbl_pd rnk_tbl_arka uac_ic_ktlr_mrgn">
				<div class="tbl_bslk">Seviye</div>
				<div class="tbl_dgr">Watson</div>
			</li>
			<li id="klnc_yn_kt" class="rnk_tbl_arka uac_ic_ktlr_mrgn">
				<div id="klnc_resim"><img src="../bunyo.jpg"/></div>
				<div id="yn_kt" class="fl_tmr">
					<div id="klnc_adi" class="rnk_klnc_yn_kt_klnc_adi el_goster">mustafa2511</div>
					<ul class="tbl_pd">
						<li id="msj" title="Mesajlar"></li>
						<li id="ayr" title="Ayarlar"></li>
						<li id="cks" title="Çıkış"></li>
					</ul>
				</div>
			</li>
		</ul>
	</div>
</div>
<div class="ust_menu fl_tmr arac_cubugu">
	<ul>
		<li>Yeni Eklenenler</li>
		<li>Favoriler</li>
		<li>En Çok Çözülenler</li>
	</ul>
</div>
<div id="dolma" class="arac_cubugu fl_tmr">
	<div id="menu">
		<dl>
			<dt>Kategoriler</dt>
			<dd>
				<ul>
					<li>Bilim</li>
					<li>Sanat</li>
					<li>Politika/Siyaset</li>
					<li>Müzik</li>
					<li>Film</li>
				</ul>
			</dd>
		</dl>
	</div>
	<div id="icerik" class="fl_tmr">
		<div id="test_akisi">
			<div class="akis">
				<div class="akis_baslik">Son Eklenenler</div>
				<div class="akis_testler fl_tmr">
					<div class="test kutu fl_tmr fl_sl">
						<img src="" class="fl_sl"/>
						<div class="test_bilgileri">
							<p class="tb_etiket">Falan Filan</p>
							<p class="tb_aciklama">uylim akuyilm ekauyimlk yulmikea yumli</p>
						</div>
						<div class="test_alt_menu">
							<input type="button" class="btn_gnl fl_sg" value="Çöz" />
						</div> 
					</div>
					<div class="test kutu fl_tmr fl_sg">
						<img src="" class="fl_sl"/>
						<div class="test_bilgileri">
							<p class="tb_etiket">Falui eauie </p>
							<p class="tb_aciklama">auie auie auie auie auiea ugğ augğ auia uiea uieayumli</p>
						</div>
						<div class="test_alt_menu">
							<input type="button" class="btn_gnl fl_sg" value="Çöz" />
						</div> 
					</div>
					<div class="test kutu fl_tmr fl_sl">
						<img src="" class="fl_sl"/>
						<div class="test_bilgileri">
							<p class="tb_etiket">Faluauie auie eauie </p>
							<p class="tb_aciklama">auie auie auie auie auiea ugğ augğ auia uiea uieayumli</p>
						</div>
						<div class="test_alt_menu">
							<input type="button" class="btn_gnl fl_sg" value="Çöz" />
						</div> 
					</div>
				</div>
			</div>
			<div class="akis">
				<div class="akis_baslik">En Son Çözülenler</div>
				<div class="akis_testler fl_tmr">
					<div class="test kutu fl_tmr fl_sl">
						<img src="" class="fl_sl"/>
						<div class="test_bilgileri">
							<p class="tb_etiket">Falan Filan</p>
							<p class="tb_aciklama">uylim akuyilm ekauyimlk yulmikea yumli</p>
						</div>
						<div class="test_alt_menu">
							<input type="button" class="btn_gnl fl_sg" value="Çöz" />
						</div> 
					</div>
					<div class="test kutu fl_tmr fl_sg">
						<img src="" class="fl_sl"/>
						<div class="test_bilgileri">
							<p class="tb_etiket">Falui eauie </p>
							<p class="tb_aciklama">auie auie auie auie auiea ugğ augğ auia uiea uieayumli</p>
						</div>
						<div class="test_alt_menu">
							<input type="button" class="btn_gnl fl_sg" value="Çöz" />
						</div> 
					</div>
					<div class="test kutu fl_tmr fl_sl">
						<img src="" class="fl_sl"/>
						<div class="test_bilgileri">
							<p class="tb_etiket">Falui eauie </p>
							<p class="tb_aciklama">auie auie auie auie auiea ugğ augğ auia uiea uieayumli</p>
						</div>
						<div class="test_alt_menu">
							<input type="button" class="btn_gnl fl_sg" value="Çöz" />
						</div> 
					</div>
				</div>
			</div>
		</div>
		<div id="listeler" class="kutu">
			<div class="liste">
				<div class="liste_baslik">
					En Çok Test Çözenler
				</div>
				<ul>
					<li>maemk234</li>
					<li>aeiğğ3</li>
					<li>maemieauk234</li>
					<li>maem uik234</li>
					<li>maeuie mk234</li>
					<li>mauie aemk234</li>
				</ul>
			</div>
			<div class="liste">
				<div class="liste_baslik">
					En Çok Çözülen Testler
				</div>
				<ul>
					<li>uağa</li>
					<li>aeui eaiğğ3</li>
					<li>mauu ie iea3emieauk234</li>
					<li>maeu ieaum uik234</li>
					<li>maeu iea uuie mk234</li>
					<li>mauui eaie aemk234</li>
				</ul>
			</div>
		</div>
	</div>
</div>
</body>
</html>