<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<link rel="stylesheet" type="text/css" href="../css/ilklendirme.css"/>
<link rel="stylesheet" type="text/css" href="../css/talil_ortak.css"/>
<link rel="stylesheet" type="text/css" href="../css/talil_anasayfa.css"/>
<link rel="stylesheet" type="text/css" href="../css/zabita.css"/>
<body>
<div id="ust_arac_cubugu" class="fl_tmr arac_cubugu">
	<div id="logo_t">
		<img src="../t.png"/>
	</div>
	<div id="uac_menu" class="fl_tmr">
		<div id="arama">
			<input type="text" id="txt_arama" name="nm_arama" class="rnk_inpt_txt_arka"/>
			<img src="../ara.png" id="ara"/>
		</div>
		<ul id="gosterge">
			<li class="tabela tbl_pd rnk_tbl_arka uac_ic_ktlr_mrgn">
				<div class="tbl_bslk">Puan</div>
				<div class="tbl_dgr">23423423</div>
			</li>
			<li class="tabela tbl_pd rnk_tbl_arka uac_ic_ktlr_mrgn">
				<div class="tbl_bslk">Seviye</div>
				<div class="tbl_dgr">Watson</div>
			</li>
			<li id="klnc_yn_kt" class="rnk_tbl_arka uac_ic_ktlr_mrgn">
				<div id="klnc_resim"><img src="../bunyo.jpg"/></div>
				<div id="yn_kt" class="fl_tmr">
					<div id="klnc_adi" class="rnk_klnc_yn_kt_klnc_adi el_goster">mustafa2511</div>
					<ul class="tbl_pd">
						<li id="msj" title="Mesajlar"></li>
						<li id="ayr" title="Ayarlar"></li>
						<li id="cks" title="Çıkış"></li>
					</ul>
				</div>
			</li>
		</ul>
	</div>
</div>
<div class="ust_menu fl_tmr arac_cubugu">
	<ul>
		<li>Yeni Eklenenler</li>
		<li>Favoriler</li>
		<li>En Çok Çözülenler</li>
	</ul>
</div>
<div id="dolma" class="arac_cubugu fl_tmr">
	<div id="menu">
		<dl>
			<dt>Kategoriler</dt>
			<dd>
				<ul>
					<li>Bilim</li>
					<li>Sanat</li>
					<li>Politika/Siyaset</li>
					<li>Müzik</li>
					<li>Film</li>
				</ul>
			</dd>
		</dl>
	</div>
	<div id="icerik">
		<div id="test">
			<div id="bilgiler">
				<span><b>Test No: #222</b> - Falan Filan</span>
				<span class="kydr_sg_4"><b>Kategori:</b>Bilim</span>
			</div>
			<div id="soru" class="kutu">
				<img>
				<div id="soru_icerik">
					<p id="soru_konum"><b>1</b>/24</p>
					<p id="soru_metin">umieyk amkuygğmk ahuikeylakm uiymek auygğnhk uikay umlikeamlu?</p>
					<div id="siklar">
						<div><label><input type="radio" name="cevap"/><span><b>A) </b>uieka ylmuikeyaml kuyilmka yuimle</span></label></div>
						<div><label><input type="radio" name="cevap"/><span><b>A) </b>uiüi ea kuyilmka yuimle</span></label></div>
						<div><label><input type="radio" name="cevap"/><span><b>A) </b>uieüyilmka yuimle</span></label></div>
						<div><label><input type="radio" name="cevap"/><span><b>A) </b>uieka ylmuikeyaml kuyilmka yuimle</span></label></div>
						<div><label><input type="radio" name="cevap"/><span><b>A) </b>uiüi ea kuyilmka yuimle</span></label></div>
						<div><label><input type="radio" name="cevap"/><span><b>A) </b>uieüyilmka yuimle</span></label></div>
						<div><label><input type="radio" name="cevap"/><span><b>A) </b>uieka ylmuikeyaml kuyilmka yuimle</span></label></div>
						<div><label><input type="radio" name="cevap"/><span><b>A) </b>uiüi ea kuyilmka yuimle</span></label></div>
						<div><label><input type="radio" name="cevap"/><span><b>A) </b>uieüyilmka yuimle</span></label></div>
					</div>
				</div>
			</div>
			<div id="soru_navigasyon" class="rnk_mn_arka t_orta">
				<input type="button" class="btn_gnl" value="Önceki Soru"/>
				<input type="button" class="btn_gnl" value="Sonraki Soru"/>
			</div>
			<div id="islemler">
				<ul>
					<li><input type="button" class="btn_gnl" value="Cevaplarımı Kaydet"/></li>
					<li class="aciklama">* test çözümüne daha sonra devam etmeniz için verdiğiniz cevapları kaydededer.</li>
					<li><input type="button" class="btn_gnl" value="Cevaplarımı Gönder"/></li>
					<li class="aciklama">* cevaplarınızı değerlendirmek üzere gönderir. Bu işlemi geri alamazsınız.</li>
					<li><input type="button" class="btn_gnl" value="Vazgeç"/></li>
				</ul>
			</div>
		</div>
	</div>
</div>
</body>
</html>