<?php include 'tl_as_ust.phtml'; ?>
<div id="sarma" class="arac_cubugu">
	<div id="baslik">Mesajlar</div>
	<div class="ust_menu fl_tmr">
		<ul id="mesaj_menu">
			<li class="rnk_mn_aktif">Gelen Kutusu (81)</li>
			<li>Çöp Kutusu (2)</li>
			<li>Okunmuş (77)</li>
			<li>Okunmamış (4)</li>
		</ul>
	</div>
	<div id="mesajlar">
		<div id="liste" class="rnk_btn_arka">
			<table>
				<thead>
					<tr>
						<th id="sec"><input type="checkbox"/></th>
						<th id="sira"></th>
						<th id="gonderen">Gönderen</th>
						<th id="tarih">Tarih</th>
						<th id="konu">Konu</th>
						<th id="durum">Durum</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><input type="checkbox"/></td>
						<td>1.</td>
						<td>aulimeak2</td>
						<td>21/50/28282 33:34:334</td>
						<td>YLauiym kuayi mkeauy...</td>
						<td>Okunmuş</td>
					</tr>
				</tbody>
			</table>
			<div id="islem">
				Seçilileri
				<select>
					<option selected value="0">İşlem Seçiniz...</option>
					<option value="1">Sil</option>
					<option value="2">Okunmuş İşaretle</option>
					<option value="3">Okunmamış İşaretle</option>
				</select>
				<input type="button" class="btn_gnl" value="Git"/>
			</div>
			<div id="mesaj_navigasyon" class="t_orta navigasyon">
				<div id="once">
					<a href="javascript:void(0);" id="en_ilk">&lt;&lt;</a>
					<a href="javascript:void(0);" id="onceki" class="nav_bosluk">&lt;</a>
				</div>
				<div id="sayilar" class="nav_sayilar_bosluk">
					<a href="javascript:void(0);">1</a>
					<a href="javascript:void(0);">2</a>
					<a href="javascript:void(0);">3</a>
					<a href="javascript:void(0);">4</a>
					<a href="javascript:void(0);">5</a>
				</div>
				<div id="sonra">
					<a href="javascript:void(0);" id="sonraki">&gt;</a>
					<a href="javascript:void(0);" id="en_son" class="nav_bosluk">&gt;&gt;</a>
				</div>
			</div>
		</div>
		<div id="icerik" class="rnk_btn_arka">
			<p><b>Gönderen:</b> zamğaml33</p>
			<p><b>Konu:</b> uyilem akugn uilyemk auyime</p>
			<p><b>Mesaj:</b></p>
			<p>uyliemk auyimlek ayulmike amlukgğnhak uimleka ulyimeka uyi meka uiuyim ekauyimlek 
			uie lmaukiyeml kauyimek uylimek </p>
		</div>
	</div>
</div>
</body>
</html>