<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="tr" xmlns="http://www.w3.org/1999/xhtml" ng-app<?php if (isset($uygulama_adi)) echo "=".$uygulama_adi;?>>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $baslik; ?></title>
<?php if (count($diziCSS) > 0): ?>
<?php foreach ($diziCSS as $CSS):?>
<link rel="stylesheet" type="text/css" href="<?php echo $CSS;?>"/>
<?php endforeach;?>
<?php endif;?>
</head>
<body>
<?php echo $govde; ?>
<?php if (count($diziJS) > 0): ?>
<?php foreach ($diziJS as $JS):?>
<script type="text/javascript" src="<?php echo $JS; ?>"></script>
<?php endforeach;?>
<?php endif;?>
<?php if ($scriptJS != ""):?>
<?php echo '<script type="text/javascript">'.$scriptJS.'</script>'; ?>
<?php endif;?>
</body>
</html>